apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappport
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webappport
  template:
    metadata:
      labels:
        app: webappport
    spec:
      containers:
      - name: webappport
        image: vigneshlucky000/zomato-clone:36
        ports:
        - containerPort: 80
