# I'm doing this to check alert is working or not which i hv recently created using prometheus rule alertmanager 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappport
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webappport
  template:
    metadata:
      labels:
        app: webappport
    spec:
      containers:
      - name: webappport
        image: vigneshlucky000/zomato-clone:4
        ports:
        - containerPort: 80
#
